"""
Django settings for MediosBasicos project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from django.conf.global_settings import LOGIN_URL
from system.libs.database import DATABASES_CONFIG

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x6in1(_rod(k_82q*#vnedzy&-$%f0($7@7txehw(&%q^ur#38'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    # Django Jet
    'jet.dashboard',
    'jet',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django Rest Framework
    'rest_framework',

    # Django Cross-Origin Resource Sharing (CORS)
    'corsheaders',

    # System App
    'system.apps.SystemConfig'
]

MIDDLEWARE = [
    # Middleware de seguridad para el sistema (X-Frame, CSRF, Cors and others)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kernel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kernel.wsgi.application'

# Cache
# Cache time to live is 15 minutes.

CACHE_TTL = 60 * 15

CORS_ORIGIN_ALLOW_ALL = True

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': DATABASES_CONFIG['sqlite3']  # Database in SQLite
    # 'default': DATABASES_CONFIG['postgresql']  # Database in PostGreSQL
    # 'default': DATABASES_CONFIG['mysql']  # Database in MySQL
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Sistema de autenticacion a utilizar
AUTHENTICATION_BACKENDS = [
    'system.managers.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login configuration
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin'
LOGOUT_REDIRECT_URL = '/'


# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'system.serializers.PageNumberSizePagination',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.DjangoModelPermissions'
    ),
    'PAGE_SIZE': 50
}


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = str(BASE_DIR / 'assets')
STATICFILES_DIRS = (
    str(BASE_DIR / 'static'),
)

MEDIA_ROOT = str(BASE_DIR / 'media')
MEDIA_URL = '/media/'

SITE_ID = 1


# Email Configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.email.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'email@server.com'
EMAIL_HOST_PASSWORD = 'password'


#######################################
#         LDAP CONFIGURATION          #
#######################################

LDAP_ENABLE = True

# Direccion del servidor ldap
LDAP_SERVER_URL = "ldap://10.0.0.3"

# Usuario para inicializar
LDAP_DN_STRING = "cn=ad search, ou=Systems, ou=UCI Domain Impersonals, dc=uci, dc=cu"

# Clave del usuario a inicializar
LDAP_PASSWORD = 'uF2SODWAHiW0eJboFFQEAvVzJ'

# CN de los usuarios en el ldap
LDAP_CONTEXT = 'OU=uci domain users,DC=uci,DC=cu'
